const express = require("express");
const router = express.Router();
const { Signup, Login, verifyOtp, getUserByMail, changePassword, getAllPayments, getAllUsersData } = require("../Controllers/userController");
const { createOrder, paymentVerification, updateUserSubscription } = require("../Controllers/PaymentCtrl");
router.post("/signup", Signup);
router.post("/verify-otp", verifyOtp);
router.post("/checkout", createOrder);
router.post("/payment/paymentverification", paymentVerification);
router.post("/updateUserSubscription", updateUserSubscription);
router.post("/login", Login);
router.post("/getUserByMail", getUserByMail);
router.post("/change-password", changePassword);
router.get("/getAllPayments", getAllPayments);
router.get("/getAllUsersData", getAllUsersData);
module.exports = router;
