const express = require("express");
const router = express.Router();
const { Signup, Login, verifyOtp } = require("../Controllers/userController");
const { createOrder, paymentVerification, updateUserSubscription } = require("../Controllers/PaymentCtrl");
router.post("/signup", Signup);
router.post("/verify-otp", verifyOtp);
router.post("/checkout", createOrder);
router.post("/paymentVerification", paymentVerification);
router.post("/updateUserSubscription", updateUserSubscription);
router.post("/login", Login);
module.exports = router;
